"""last_seen changed to signed_up_date

Revision ID: f621fa377a99
Revises: 0f17a2d3e376
Create Date: 2022-07-28 11:24:09.108587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f621fa377a99'
down_revision = '0f17a2d3e376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signed_up_date', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'signed_up_date')
    # ### end Alembic commands ###
